import { compareSemanticVersions } from "../../lib/semver.js";
import type { PackageManager } from "../../lib/types.js";
import { coreMigrationActions } from "./migrations.js";
import type {
  UpgradeAction,
  UpgradeContext,
  UpgradePlan,
  UpgradeStatus,
} from "./types.js";

function installCommand(packageManager: PackageManager): string {
  if (packageManager === "pnpm") return "pnpm install --frozen-lockfile";
  if (packageManager === "bun") return "bun install --frozen-lockfile";
  return "npm ci";
}

function engineUpgradeCommand(context: UpgradeContext): string {
  const dependency = `authenik8-core@${context.targetEngineVersion}`;
  if (context.packageManager === "pnpm") return `pnpm add ${dependency}`;
  if (context.packageManager === "bun") return `bun add ${dependency}`;
  if (context.manifest.preset === "fullstack") {
    return `npm install ${dependency} --workspace @authenik8/api`;
  }
  return `npm install ${dependency}`;
}

function blockedAction(id: string, title: string, detail: string): UpgradeAction {
  return { id, kind: "blocked", title, detail };
}

export function createUpgradePlan(context: UpgradeContext): UpgradePlan {
  const actions: UpgradeAction[] = [];
  let status: UpgradeStatus = "current";

  if (context.declaredEngineVersion !== context.manifest.engine.version) {
    actions.push(blockedAction(
      "engine.manifest-drift",
      "Reconcile the engine declaration and project manifest",
      `package.json declares ${context.declaredEngineVersion}, while authenik8.json records ${context.manifest.engine.version}. Doctor must pass before an upgrade is planned.`,
    ));
    status = "blocked";
  }
  if (
    context.installedEngineVersion
    && context.installedEngineVersion !== context.declaredEngineVersion
  ) {
    actions.push(blockedAction(
      "engine.install-drift",
      "Restore a reproducible dependency installation",
      `Installed authenik8-core ${context.installedEngineVersion} does not match the ${context.declaredEngineVersion} declaration. Restore the lockfile installation before upgrading.`,
    ));
    status = "blocked";
  } else if (!context.installedEngineVersion) {
    actions.push({
      id: "dependencies.install",
      kind: "recommended",
      title: "Install the declared dependency graph before validation",
      detail: "The plan can compare declarations without node_modules, but Doctor must inspect the installed identity engine before an auth change is accepted.",
      command: installCommand(context.packageManager),
    });
  }

  const generatorOrder = compareSemanticVersions(
    context.manifest.generatedBy.version,
    context.targetGeneratorVersion,
  );
  if (generatorOrder === "invalid") {
    actions.push(blockedAction(
      "generator.invalid-version",
      "Use a semantic generator version",
      `Cannot compare project generator version ${context.manifest.generatedBy.version} with ${context.targetGeneratorVersion}.`,
    ));
    status = "blocked";
  } else if (generatorOrder === "newer") {
    actions.push(blockedAction(
      "generator.downgrade",
      "Use a CLI that is at least as new as the project",
      `This project was generated by ${context.manifest.generatedBy.version}; the running CLI is ${context.targetGeneratorVersion} and cannot safely plan a downgrade.`,
    ));
    status = "blocked";
  } else if (generatorOrder === "older") {
    actions.push({
      id: "generator.release-review",
      kind: "required",
      title: `Review generator changes through ${context.targetGeneratorVersion}`,
      detail: "Generator upgrades are never inferred as source rewrites. Review the release notes and preview explicit add or migration recipes on a branch.",
      references: ["create-authenik8-app release notes", "authenik8.json"],
    });
    if (status !== "blocked") status = "upgrade-available";
  }

  const engineOrder = compareSemanticVersions(
    context.manifest.engine.version,
    context.targetEngineVersion,
  );
  if (engineOrder === "invalid") {
    actions.push(blockedAction(
      "engine.invalid-version",
      "Use an exact semantic engine version",
      `Cannot compare project engine version ${context.manifest.engine.version} with ${context.targetEngineVersion}.`,
    ));
    status = "blocked";
  } else if (engineOrder === "newer") {
    actions.push(blockedAction(
      "engine.downgrade",
      "Use a CLI compatible with the declared identity engine",
      `The project targets authenik8-core ${context.manifest.engine.version}, newer than this CLI's ${context.targetEngineVersion} template contract.`,
    ));
    status = "blocked";
  } else if (engineOrder === "older") {
    actions.push(...coreMigrationActions(
      context.manifest.engine.version,
      context.targetEngineVersion,
    ));
    actions.push({
      id: "engine.upgrade",
      kind: "required",
      title: `Upgrade authenik8-core to ${context.targetEngineVersion}`,
      detail: "Apply this only after reviewing every security-boundary action above. Keep the manifest unchanged until the dependency, generated integration, and Doctor all agree.",
      command: engineUpgradeCommand(context),
      references: ["authenik8-core CHANGELOG.md"],
    });
    if (status !== "blocked") status = "upgrade-available";
  }

  if (status === "upgrade-available") {
    actions.push({
      id: "upgrade.verify",
      kind: "required",
      title: "Validate the upgraded auth boundary before updating metadata",
      detail: "Run static and live-service diagnostics, exercise login, refresh rotation, OAuth callbacks, linking, and authorization, then update authenik8.json as the final audited change.",
      command: `npx create-authenik8-app@${context.targetGeneratorVersion} doctor`,
      references: ["THREAT_MODEL.md"],
    });
  }

  return {
    schemaVersion: 1,
    rootDir: context.rootDir,
    preset: context.manifest.preset,
    status,
    versions: {
      generator: {
        project: context.manifest.generatedBy.version,
        target: context.targetGeneratorVersion,
      },
      engine: {
        manifest: context.manifest.engine.version,
        declared: context.declaredEngineVersion,
        ...(context.installedEngineVersion
          ? { installed: context.installedEngineVersion }
          : {}),
        target: context.targetEngineVersion,
      },
    },
    actions,
  };
}
